runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /incl
  static_dir: incl

- url: /tasks/fetch
  script: fetch.app

- url: /.*
  script: index.app

libraries:
- name: webapp2
  version: latest
